### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by miya-shoya** [miya-shoya/protospace-40044#1]
自身のProtoSpaceのURL（本番環境）
https://protospace-40044.onrender.com/

**Comment by snkw-works** [comment]
@miya-shoya さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### プロトタイプ一覧表示機能
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
プロトタイプ名をクリックした時に詳細ページに遷移しない状態です。

#### コメント機能
- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
空欄でも投稿ができてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miya-shoya** [comment]
修正したので確認お願いします
https://protospace-40044.onrender.com/

**Comment by mo1015** [comment]
@miya-shoya さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
